AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an S3 bucket for hosting the frontend.

Resources:
  FrontendBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend-bucket"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"

Outputs:
  FrontendBucketName:
    Description: "S3 Bucket Name for the Frontend"
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${AWS::StackName}-FrontendBucketName"
